from evdev import ecodes as e

erika2uinput = [
    # 0
    None,
    ['_'],
    ['&'],
    ['" (no step)'],
    ['%'],
    ['i'],
    ['£'],
    ['µ'],
    ['9'],
    ['8'],
    ['7'],
    ['6'],
    ['5'],
    ['0'],
    ['4'],
    ['3'],
    # 1
    ['2'],
    ['1'],
    ['H'],
    [':'],
    ['D'],
    ['²'],
    ['M'],
    ['\''],
    ['B'],
    ['^ (no step)'],
    ['Q'],
    ['*'],
    ['G'],
    ['('],
    ['O'],
    [')'],
    # 2
    ['C'],
    ['I'],
    ['V'],
    ['³'],
    ['K'],
    ['+'],
    ['X'],
    ['|'],
    ['U'],
    ['´ (no step)'],
    ['N'],
    ['`'],
    ['L'],
    ['W'],
    ['='],
    ['P'],
    # 3
    ['A'],
    ['Y'],
    ['J'],
    ['S'],
    ['E'],
    ['?'],
    ['R'],
    ['T'],
    ['Z'],
    ['°'],
    ['Ü'],
    [';'],
    ['Ö'],
    ['§'],
    ['F'],
    ['Ä'],
    # 4
    ['/'],
    ['#'],
    ['!'],
    ['"'],
    ['é'],
    ['ç'],
    ['è'],
    ['ß'],
    ['$'],
    ['f'],
    ['m'],
    ['j'],
    ['w'],
    ['l'],
    ['b'],
    ['v'],
    # 5
    ['k'],
    ['y'],
    ['q'],
    ['d'],
    ['z'],
    ['h'],
    ['t'],
    ['c'],
    ['s'],
    ['r'],
    ['e'],
    ['p'],
    ['n'],
    ['u'],
    ['o'],
    ['x'],
    # 6
    ['g'],
    ['a',[e.KEY_A,1,e.KEY_A,0]],
    ['-'],
    ['.'],
    [','],
    ['ä'],
    ['ö'],
    ['ü'],
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    # 7
    None,
    ['Space'],          # 1 Zeichen rechts
    ['backstep'],       # 1 Zeichen links
    None,               # 1/2 Zeichen rechts 
    ['CODE backstep'],  # 1/2 Zeichen links
    ['step down'],      # 1/2 Zeile nach unten
    ['step up'],        # 1/2 Zeile nach oben
    ['Return'],         # CR+LF
    None,               # CR
    ['Tab'],            # next Tab
    ['T+'],             # Tab setzen
    ['T-'],             # Tab löschen
    ['CODE T-'],        # alle Tab löschen 
    ['CODE T+'],        # Standardtabs setzen
    ['Set Rand links'], # Rand links setzen
    ['Set Rand rechts'],# Rand rechts setzen
    # 8
    ['Rand lösen'],     # Rand lösen
    ['CODE step down'], # 1/20 Zeile nach unten
    ['CODE step up'],   # 1/20 Zeile nach oben
    ['form feed'],      # Papiereinzug
    ['1 zeilig (stat)'],# Zeilenabstand 1
    ['1,5 zeilig (stat)'],# Zeilenabstand 1,5
    ['2 zeilig (stat)'],# Zeilenabstand 2
    ['10 cpi (stat)'],  # 10 cpi
    ['12 cpi (stat)'],  # 12 cpi
    ['15 cpi (stat)'],  # 15 cpi
    None,
    None,               # set delete off 
    None,               # set delete on
    None,               # Rückwärtsdruck aus
    None,               # Rückwärtsdruck an
    None,               # Randlösen dauerhaft an
    # 9
    None,               # Randlösen dauerhaft aus 
    None,               # echo off
    None,               # echo on
    None,               # reset
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    ['CODE S'],
    None,
    # A
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    # B
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    ['CODE switch!'],
    None,
    None,
    None,
    None,
    # C
    ['MODE 1'],
    ['MODE Q'],
    ['MODE A'],
    ['MODE Y'],
    ['MODE 2'],
    ['MODE W'],
    ['MODE S'],
    ['MODE X'],
    ['MODE 3'],
    ['MODE E'],
    ['MODE D'],
    ['MODE C'],
    ['MODE 4'],
    ['MODE R'],
    ['MODE F'],
    ['MODE V'],
    # D
    ['MODE 5'],
    ['MODE T'],
    ['MODE G'],
    ['MODE B'],
    ['MODE 6'],
    ['MODE Z'],
    ['MODE H'],
    ['MODE N'],
    ['MODE 7'],
    ['MODE U'],
    ['MODE J'],
    ['MODE M'],
    ['MODE 8'],
    ['MODE I'],
    ['MODE K'],
    ['MODE ,'],
    # E
    ['MODE 9'],
    ['MODE O'],
    ['MODE L'],
    ['MODE .'],
    ['MODE 0'],
    ['MODE P'],
    ['MODE Ö'],
    ['MODE -'],
    ['MODE ß'],
    ['MODE Ü'],
    ['MODE Ä'],
    ['REL'],
    ['MODE acutes'],
    [13],
    ['CODE REL'],
    [15],
    # F
    None,
    None,
    None,
    None,
    ['MODE T+'],
    ['MODE T-'],
    None,
    ['CODE backspace'],
    ['2 zeilig (key)'],
    ['1 zeilig (key)'],
    ['10 CPI'],
    ['MODE backspace'],
    ['backspace'],
    ['MODE form feed'],
    ['1,5 zeilig (key)'],
    ['12 CPI'],
    # 10
    None,
    ['CODE Q'],
    ['CODE A'],
    ['CODE Y'],
    None,
    ['CODE W'],
    ['CODE S'],
    ['CODE X'],
    None,
    ['CODE E'],
    ['CODE D'],
    ['CODE C'],
    None,
    ['CODE R'],
    ['CODE F'],
    ['CODE V'],
    # 11
    None,
    ['CODE T'],
    ['CODE G'],
    ['CODE B'],
    None,
    ['CODE Z'],
    ['CODE H'],
    ['CODE N'],
    None,
    ['CODE U'],
    ['CODE J'],
    ['CODE M'],
    None,
    ['CODE I'],
    ['CODE K'],
    ['CODE ,'],
    # 12
    None,
    ['CODE O'],
    ['CODE L'],
    ['CODE .'],
    None,
    ['CODE P'],
    ['CODE Ö'],
    None,
    None,
    ['CODE Ü'],
    ['CODE Ä']
]